name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Create .env.production from GitHub Secret
        run: echo "$VERCEL_ENV" > .env.production
        env:
          VERCEL_ENV: ${{ secrets.VERCEL_ENV }}

      - name: Link Vercel Project
        run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Import env vars into Vercel
        run: vercel env pull .env.production --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy to Vercel (Production)
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}